export const USER_DETAIL_NS = "userDetail";
export const USER_DETAIL_INFO_NS = "userDetailInfo";
export const USER_DETAIL_EPISODES_NS = "userDetailEpisodes";

export const FETCH_USER_DETAIL_REQUEST = "FETCH_USER_DETAIL_REQUEST";
export const FETCH_USER_DETAIL_SUCCESS = "FETCH_USER_DETAIL_SUCCESS";
export const FETCH_USER_DETAIL_ERROR = "FETCH_USER_DETAIL_ERROR";

export const FETCH_USER_DETAIL_EPISODES_REQUEST =
  "FETCH_USER_DETAIL_EPISODES_REQUEST";
export const FETCH_USER_DETAIL_EPISODES_SUCCESS =
  "FETCH_USER_DETAIL_EPISODES_SUCCESS";
export const FETCH_USER_DETAIL_EPISODES_ERROR =
  "FETCH_USER_DETAIL_EPISODES_ERROR";
export const RESET_USER_DETAIL_EPISODES = "RESET_USER_DETAIL_EPISODES";
